// JSON Schema
// Used to validate data in the redux store
// Generated by https://jsonschema.net/
export default {
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/root.json",
    "type": "object",
    "title": "The Root Schema",
    "required": [
        "comments",
        "auth"
    ],
    "properties": {
        "comments": {
            "$id": "#/properties/comments",
            "type": "array",
            "title": "The Comments Schema",
            "items": {
                "$id": "#/properties/comments/items",
                "type": "string",
                "title": "The Items Schema",
                "default": "",
                "examples": [
                    "laudantium enim quasi est quidem magnam voluptate ipsam eos tempora quo necessitatibus dolor quam autem quasi reiciendis et nam sapiente accusantium",
                    "laudantium enim quasi est quidem magnam voluptate ipsam eos tempora quo necessitatibus dolor quam autem quasi reiciendis et nam sapiente accusantium"
                ],
                "pattern": "^(.*)$"
            }
        },
        "auth": {
            "$id": "#/properties/auth",
            "type": "boolean",
            "title": "The Auth Schema",
            "default": false,
            "examples": [
                false
            ]
        }
    }
}
